apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: memcached-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Memcached is the Schema for the memcacheds API
      displayName: Memcached
      kind: Memcached
      name: memcacheds.cache.example.com
      version: v1alpha1
  description: memcached-operator-essie
  displayName: make bundle-build bundle-push BUNDLE_IMG="quay.io/jysjiangwork/memcached-operator-bundle:v0.0.1"
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - essie
  - learn
  - operator
  links:
  - name: Memcached Operator
    url: https://memcached-operator.domain
  maintainers:
  - email: yishanj13@gmail.com
    name: essie
  maturity: alpha
  provider:
    name: TEST
  version: 0.0.0
